spring:
  application:
    name: security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin123
    url: jdbc:mysql://localhost:3306/security_test?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
  security:
   user:
     name: gayan
     password: gayan
#    properties:
#      hibernate.hibernate.dialect: org.hibernate.dialect
server:
  port: 8090